/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PerfilIndexRouteImport } from './routes/perfil.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PerfilExplorarRouteImport } from './routes/perfil.explorar'
import { Route as PerfilComprasRouteImport } from './routes/perfil.compras'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as PintarSlugPageRouteImport } from './routes/pintar.$slug.$page'
import { Route as AdminShellWebhooksRouteImport } from './routes/admin/_shell/webhooks'
import { Route as AdminShellVerComoUsuarioRouteImport } from './routes/admin/_shell/ver-como-usuario'
import { Route as AdminShellUsuariosRouteImport } from './routes/admin/_shell/usuarios'
import { Route as AdminShellTemplatesRouteImport } from './routes/admin/_shell/templates'
import { Route as AdminShellQaCapasRouteImport } from './routes/admin/_shell/qa-capas'
import { Route as AdminShellPlanosRouteImport } from './routes/admin/_shell/planos'
import { Route as AdminShellOfertasRouteImport } from './routes/admin/_shell/ofertas'
import { Route as AdminShellIdiomasRouteImport } from './routes/admin/_shell/idiomas'
import { Route as AdminShellHospedarVideosRouteImport } from './routes/admin/_shell/hospedar-videos'
import { Route as AdminShellEspionarOfertasRouteImport } from './routes/admin/_shell/espionar-ofertas'
import { Route as AdminShellDashboardRouteImport } from './routes/admin/_shell/dashboard'
import { Route as AdminShellCriarQuizRouteImport } from './routes/admin/_shell/criar-quiz'
import { Route as AdminShellCriarEClonarSitesRouteImport } from './routes/admin/_shell/criar-e-clonar-sites'
import { Route as AdminShellCoresRouteImport } from './routes/admin/_shell/cores'
import { Route as AdminShellCatalogoRouteImport } from './routes/admin/_shell/catalogo'
import { Route as AdminShellCadastrarProdutoRouteImport } from './routes/admin/_shell/cadastrar-produto'
import { Route as AdminShellCadastrarPerfectPayRouteImport } from './routes/admin/_shell/cadastrar-perfect-pay'
import { Route as AdminShellBrandingRouteImport } from './routes/admin/_shell/branding'
import { Route as AdminShellAreasMembrosRouteImport } from './routes/admin/_shell/areas-membros'
import { Route as AdminShellAreasRouteImport } from './routes/admin/_shell/areas'
import { Route as ApiPublicPerfectpayWebhookRouteImport } from './routes/api/public/perfectpay.webhook'
import { Route as AdminShellUsuariosUserIdRouteImport } from './routes/admin/_shell/usuarios.$userId'
import { Route as AdminShellFerramentasSlugRouteImport } from './routes/admin/_shell/ferramentas.$slug'
import { Route as AdminShellBibliotecaDownloadsRouteImport } from './routes/admin/_shell/biblioteca.downloads'
import { Route as AdminShellBibliotecaDesenhosRouteImport } from './routes/admin/_shell/biblioteca.desenhos'
import { Route as AdminShellBibliotecaCursosRouteImport } from './routes/admin/_shell/biblioteca.cursos'
import { Route as AdminShellAreasAreaIdRouteImport } from './routes/admin/_shell/areas.$areaId'
import { Route as AdminShellProdutosProductIdEbookRouteImport } from './routes/admin/_shell/produtos.$productId.ebook'
import { Route as AdminShellProdutosProductIdAulasRouteImport } from './routes/admin/_shell/produtos.$productId.aulas'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIndexRoute = PerfilIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PerfilRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilExplorarRoute = PerfilExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => PerfilRoute,
} as any)
const PerfilComprasRoute = PerfilComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => PerfilRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/admin/_shell',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PintarSlugPageRoute = PintarSlugPageRouteImport.update({
  id: '/pintar/$slug/$page',
  path: '/pintar/$slug/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellWebhooksRoute = AdminShellWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellVerComoUsuarioRoute =
  AdminShellVerComoUsuarioRouteImport.update({
    id: '/ver-como-usuario',
    path: '/ver-como-usuario',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellUsuariosRoute = AdminShellUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellTemplatesRoute = AdminShellTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellQaCapasRoute = AdminShellQaCapasRouteImport.update({
  id: '/qa-capas',
  path: '/qa-capas',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellPlanosRoute = AdminShellPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellOfertasRoute = AdminShellOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellIdiomasRoute = AdminShellIdiomasRouteImport.update({
  id: '/idiomas',
  path: '/idiomas',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellHospedarVideosRoute =
  AdminShellHospedarVideosRouteImport.update({
    id: '/hospedar-videos',
    path: '/hospedar-videos',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellEspionarOfertasRoute =
  AdminShellEspionarOfertasRouteImport.update({
    id: '/espionar-ofertas',
    path: '/espionar-ofertas',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellDashboardRoute = AdminShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellCriarQuizRoute = AdminShellCriarQuizRouteImport.update({
  id: '/criar-quiz',
  path: '/criar-quiz',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellCriarEClonarSitesRoute =
  AdminShellCriarEClonarSitesRouteImport.update({
    id: '/criar-e-clonar-sites',
    path: '/criar-e-clonar-sites',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellCoresRoute = AdminShellCoresRouteImport.update({
  id: '/cores',
  path: '/cores',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellCatalogoRoute = AdminShellCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellCadastrarProdutoRoute =
  AdminShellCadastrarProdutoRouteImport.update({
    id: '/cadastrar-produto',
    path: '/cadastrar-produto',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellCadastrarPerfectPayRoute =
  AdminShellCadastrarPerfectPayRouteImport.update({
    id: '/cadastrar-perfect-pay',
    path: '/cadastrar-perfect-pay',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellBrandingRoute = AdminShellBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAreasMembrosRoute = AdminShellAreasMembrosRouteImport.update({
  id: '/areas-membros',
  path: '/areas-membros',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAreasRoute = AdminShellAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AdminShellRoute,
} as any)
const ApiPublicPerfectpayWebhookRoute =
  ApiPublicPerfectpayWebhookRouteImport.update({
    id: '/api/public/perfectpay/webhook',
    path: '/api/public/perfectpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminShellUsuariosUserIdRoute =
  AdminShellUsuariosUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AdminShellUsuariosRoute,
  } as any)
const AdminShellFerramentasSlugRoute =
  AdminShellFerramentasSlugRouteImport.update({
    id: '/ferramentas/$slug',
    path: '/ferramentas/$slug',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellBibliotecaDownloadsRoute =
  AdminShellBibliotecaDownloadsRouteImport.update({
    id: '/biblioteca/downloads',
    path: '/biblioteca/downloads',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellBibliotecaDesenhosRoute =
  AdminShellBibliotecaDesenhosRouteImport.update({
    id: '/biblioteca/desenhos',
    path: '/biblioteca/desenhos',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellBibliotecaCursosRoute =
  AdminShellBibliotecaCursosRouteImport.update({
    id: '/biblioteca/cursos',
    path: '/biblioteca/cursos',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellAreasAreaIdRoute = AdminShellAreasAreaIdRouteImport.update({
  id: '/$areaId',
  path: '/$areaId',
  getParentRoute: () => AdminShellAreasRoute,
} as any)
const AdminShellProdutosProductIdEbookRoute =
  AdminShellProdutosProductIdEbookRouteImport.update({
    id: '/produtos/$productId/ebook',
    path: '/produtos/$productId/ebook',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellProdutosProductIdAulasRoute =
  AdminShellProdutosProductIdAulasRouteImport.update({
    id: '/produtos/$productId/aulas',
    path: '/produtos/$productId/aulas',
    getParentRoute: () => AdminShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/perfil/compras': typeof PerfilComprasRoute
  '/perfil/explorar': typeof PerfilExplorarRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/admin/areas': typeof AdminShellAreasRouteWithChildren
  '/admin/areas-membros': typeof AdminShellAreasMembrosRoute
  '/admin/branding': typeof AdminShellBrandingRoute
  '/admin/cadastrar-perfect-pay': typeof AdminShellCadastrarPerfectPayRoute
  '/admin/cadastrar-produto': typeof AdminShellCadastrarProdutoRoute
  '/admin/catalogo': typeof AdminShellCatalogoRoute
  '/admin/cores': typeof AdminShellCoresRoute
  '/admin/criar-e-clonar-sites': typeof AdminShellCriarEClonarSitesRoute
  '/admin/criar-quiz': typeof AdminShellCriarQuizRoute
  '/admin/dashboard': typeof AdminShellDashboardRoute
  '/admin/espionar-ofertas': typeof AdminShellEspionarOfertasRoute
  '/admin/hospedar-videos': typeof AdminShellHospedarVideosRoute
  '/admin/idiomas': typeof AdminShellIdiomasRoute
  '/admin/ofertas': typeof AdminShellOfertasRoute
  '/admin/planos': typeof AdminShellPlanosRoute
  '/admin/qa-capas': typeof AdminShellQaCapasRoute
  '/admin/templates': typeof AdminShellTemplatesRoute
  '/admin/usuarios': typeof AdminShellUsuariosRouteWithChildren
  '/admin/ver-como-usuario': typeof AdminShellVerComoUsuarioRoute
  '/admin/webhooks': typeof AdminShellWebhooksRoute
  '/pintar/$slug/$page': typeof PintarSlugPageRoute
  '/admin/areas/$areaId': typeof AdminShellAreasAreaIdRoute
  '/admin/biblioteca/cursos': typeof AdminShellBibliotecaCursosRoute
  '/admin/biblioteca/desenhos': typeof AdminShellBibliotecaDesenhosRoute
  '/admin/biblioteca/downloads': typeof AdminShellBibliotecaDownloadsRoute
  '/admin/ferramentas/$slug': typeof AdminShellFerramentasSlugRoute
  '/admin/usuarios/$userId': typeof AdminShellUsuariosUserIdRoute
  '/api/public/perfectpay/webhook': typeof ApiPublicPerfectpayWebhookRoute
  '/admin/produtos/$productId/aulas': typeof AdminShellProdutosProductIdAulasRoute
  '/admin/produtos/$productId/ebook': typeof AdminShellProdutosProductIdEbookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/perfil/compras': typeof PerfilComprasRoute
  '/perfil/explorar': typeof PerfilExplorarRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/perfil': typeof PerfilIndexRoute
  '/admin/areas': typeof AdminShellAreasRouteWithChildren
  '/admin/areas-membros': typeof AdminShellAreasMembrosRoute
  '/admin/branding': typeof AdminShellBrandingRoute
  '/admin/cadastrar-perfect-pay': typeof AdminShellCadastrarPerfectPayRoute
  '/admin/cadastrar-produto': typeof AdminShellCadastrarProdutoRoute
  '/admin/catalogo': typeof AdminShellCatalogoRoute
  '/admin/cores': typeof AdminShellCoresRoute
  '/admin/criar-e-clonar-sites': typeof AdminShellCriarEClonarSitesRoute
  '/admin/criar-quiz': typeof AdminShellCriarQuizRoute
  '/admin/dashboard': typeof AdminShellDashboardRoute
  '/admin/espionar-ofertas': typeof AdminShellEspionarOfertasRoute
  '/admin/hospedar-videos': typeof AdminShellHospedarVideosRoute
  '/admin/idiomas': typeof AdminShellIdiomasRoute
  '/admin/ofertas': typeof AdminShellOfertasRoute
  '/admin/planos': typeof AdminShellPlanosRoute
  '/admin/qa-capas': typeof AdminShellQaCapasRoute
  '/admin/templates': typeof AdminShellTemplatesRoute
  '/admin/usuarios': typeof AdminShellUsuariosRouteWithChildren
  '/admin/ver-como-usuario': typeof AdminShellVerComoUsuarioRoute
  '/admin/webhooks': typeof AdminShellWebhooksRoute
  '/pintar/$slug/$page': typeof PintarSlugPageRoute
  '/admin/areas/$areaId': typeof AdminShellAreasAreaIdRoute
  '/admin/biblioteca/cursos': typeof AdminShellBibliotecaCursosRoute
  '/admin/biblioteca/desenhos': typeof AdminShellBibliotecaDesenhosRoute
  '/admin/biblioteca/downloads': typeof AdminShellBibliotecaDownloadsRoute
  '/admin/ferramentas/$slug': typeof AdminShellFerramentasSlugRoute
  '/admin/usuarios/$userId': typeof AdminShellUsuariosUserIdRoute
  '/api/public/perfectpay/webhook': typeof ApiPublicPerfectpayWebhookRoute
  '/admin/produtos/$productId/aulas': typeof AdminShellProdutosProductIdAulasRoute
  '/admin/produtos/$productId/ebook': typeof AdminShellProdutosProductIdEbookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/favoritos': typeof FavoritosRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRouteWithChildren
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/perfil/compras': typeof PerfilComprasRoute
  '/perfil/explorar': typeof PerfilExplorarRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/perfil/': typeof PerfilIndexRoute
  '/admin/_shell/areas': typeof AdminShellAreasRouteWithChildren
  '/admin/_shell/areas-membros': typeof AdminShellAreasMembrosRoute
  '/admin/_shell/branding': typeof AdminShellBrandingRoute
  '/admin/_shell/cadastrar-perfect-pay': typeof AdminShellCadastrarPerfectPayRoute
  '/admin/_shell/cadastrar-produto': typeof AdminShellCadastrarProdutoRoute
  '/admin/_shell/catalogo': typeof AdminShellCatalogoRoute
  '/admin/_shell/cores': typeof AdminShellCoresRoute
  '/admin/_shell/criar-e-clonar-sites': typeof AdminShellCriarEClonarSitesRoute
  '/admin/_shell/criar-quiz': typeof AdminShellCriarQuizRoute
  '/admin/_shell/dashboard': typeof AdminShellDashboardRoute
  '/admin/_shell/espionar-ofertas': typeof AdminShellEspionarOfertasRoute
  '/admin/_shell/hospedar-videos': typeof AdminShellHospedarVideosRoute
  '/admin/_shell/idiomas': typeof AdminShellIdiomasRoute
  '/admin/_shell/ofertas': typeof AdminShellOfertasRoute
  '/admin/_shell/planos': typeof AdminShellPlanosRoute
  '/admin/_shell/qa-capas': typeof AdminShellQaCapasRoute
  '/admin/_shell/templates': typeof AdminShellTemplatesRoute
  '/admin/_shell/usuarios': typeof AdminShellUsuariosRouteWithChildren
  '/admin/_shell/ver-como-usuario': typeof AdminShellVerComoUsuarioRoute
  '/admin/_shell/webhooks': typeof AdminShellWebhooksRoute
  '/pintar/$slug/$page': typeof PintarSlugPageRoute
  '/admin/_shell/areas/$areaId': typeof AdminShellAreasAreaIdRoute
  '/admin/_shell/biblioteca/cursos': typeof AdminShellBibliotecaCursosRoute
  '/admin/_shell/biblioteca/desenhos': typeof AdminShellBibliotecaDesenhosRoute
  '/admin/_shell/biblioteca/downloads': typeof AdminShellBibliotecaDownloadsRoute
  '/admin/_shell/ferramentas/$slug': typeof AdminShellFerramentasSlugRoute
  '/admin/_shell/usuarios/$userId': typeof AdminShellUsuariosUserIdRoute
  '/api/public/perfectpay/webhook': typeof ApiPublicPerfectpayWebhookRoute
  '/admin/_shell/produtos/$productId/aulas': typeof AdminShellProdutosProductIdAulasRoute
  '/admin/_shell/produtos/$productId/ebook': typeof AdminShellProdutosProductIdEbookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/favoritos'
    | '/home'
    | '/login'
    | '/perfil'
    | '/admin'
    | '/admin/login'
    | '/perfil/compras'
    | '/perfil/explorar'
    | '/produto/$slug'
    | '/admin/'
    | '/perfil/'
    | '/admin/areas'
    | '/admin/areas-membros'
    | '/admin/branding'
    | '/admin/cadastrar-perfect-pay'
    | '/admin/cadastrar-produto'
    | '/admin/catalogo'
    | '/admin/cores'
    | '/admin/criar-e-clonar-sites'
    | '/admin/criar-quiz'
    | '/admin/dashboard'
    | '/admin/espionar-ofertas'
    | '/admin/hospedar-videos'
    | '/admin/idiomas'
    | '/admin/ofertas'
    | '/admin/planos'
    | '/admin/qa-capas'
    | '/admin/templates'
    | '/admin/usuarios'
    | '/admin/ver-como-usuario'
    | '/admin/webhooks'
    | '/pintar/$slug/$page'
    | '/admin/areas/$areaId'
    | '/admin/biblioteca/cursos'
    | '/admin/biblioteca/desenhos'
    | '/admin/biblioteca/downloads'
    | '/admin/ferramentas/$slug'
    | '/admin/usuarios/$userId'
    | '/api/public/perfectpay/webhook'
    | '/admin/produtos/$productId/aulas'
    | '/admin/produtos/$productId/ebook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/favoritos'
    | '/home'
    | '/login'
    | '/admin'
    | '/admin/login'
    | '/perfil/compras'
    | '/perfil/explorar'
    | '/produto/$slug'
    | '/perfil'
    | '/admin/areas'
    | '/admin/areas-membros'
    | '/admin/branding'
    | '/admin/cadastrar-perfect-pay'
    | '/admin/cadastrar-produto'
    | '/admin/catalogo'
    | '/admin/cores'
    | '/admin/criar-e-clonar-sites'
    | '/admin/criar-quiz'
    | '/admin/dashboard'
    | '/admin/espionar-ofertas'
    | '/admin/hospedar-videos'
    | '/admin/idiomas'
    | '/admin/ofertas'
    | '/admin/planos'
    | '/admin/qa-capas'
    | '/admin/templates'
    | '/admin/usuarios'
    | '/admin/ver-como-usuario'
    | '/admin/webhooks'
    | '/pintar/$slug/$page'
    | '/admin/areas/$areaId'
    | '/admin/biblioteca/cursos'
    | '/admin/biblioteca/desenhos'
    | '/admin/biblioteca/downloads'
    | '/admin/ferramentas/$slug'
    | '/admin/usuarios/$userId'
    | '/api/public/perfectpay/webhook'
    | '/admin/produtos/$productId/aulas'
    | '/admin/produtos/$productId/ebook'
  id:
    | '__root__'
    | '/'
    | '/buscar'
    | '/favoritos'
    | '/home'
    | '/login'
    | '/perfil'
    | '/admin/_shell'
    | '/admin/login'
    | '/perfil/compras'
    | '/perfil/explorar'
    | '/produto/$slug'
    | '/admin/'
    | '/perfil/'
    | '/admin/_shell/areas'
    | '/admin/_shell/areas-membros'
    | '/admin/_shell/branding'
    | '/admin/_shell/cadastrar-perfect-pay'
    | '/admin/_shell/cadastrar-produto'
    | '/admin/_shell/catalogo'
    | '/admin/_shell/cores'
    | '/admin/_shell/criar-e-clonar-sites'
    | '/admin/_shell/criar-quiz'
    | '/admin/_shell/dashboard'
    | '/admin/_shell/espionar-ofertas'
    | '/admin/_shell/hospedar-videos'
    | '/admin/_shell/idiomas'
    | '/admin/_shell/ofertas'
    | '/admin/_shell/planos'
    | '/admin/_shell/qa-capas'
    | '/admin/_shell/templates'
    | '/admin/_shell/usuarios'
    | '/admin/_shell/ver-como-usuario'
    | '/admin/_shell/webhooks'
    | '/pintar/$slug/$page'
    | '/admin/_shell/areas/$areaId'
    | '/admin/_shell/biblioteca/cursos'
    | '/admin/_shell/biblioteca/desenhos'
    | '/admin/_shell/biblioteca/downloads'
    | '/admin/_shell/ferramentas/$slug'
    | '/admin/_shell/usuarios/$userId'
    | '/api/public/perfectpay/webhook'
    | '/admin/_shell/produtos/$productId/aulas'
    | '/admin/_shell/produtos/$productId/ebook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscarRoute: typeof BuscarRoute
  FavoritosRoute: typeof FavoritosRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRouteWithChildren
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PintarSlugPageRoute: typeof PintarSlugPageRoute
  ApiPublicPerfectpayWebhookRoute: typeof ApiPublicPerfectpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/': {
      id: '/perfil/'
      path: '/'
      fullPath: '/perfil/'
      preLoaderRoute: typeof PerfilIndexRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/explorar': {
      id: '/perfil/explorar'
      path: '/explorar'
      fullPath: '/perfil/explorar'
      preLoaderRoute: typeof PerfilExplorarRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/perfil/compras': {
      id: '/perfil/compras'
      path: '/compras'
      fullPath: '/perfil/compras'
      preLoaderRoute: typeof PerfilComprasRouteImport
      parentRoute: typeof PerfilRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pintar/$slug/$page': {
      id: '/pintar/$slug/$page'
      path: '/pintar/$slug/$page'
      fullPath: '/pintar/$slug/$page'
      preLoaderRoute: typeof PintarSlugPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/webhooks': {
      id: '/admin/_shell/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminShellWebhooksRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/ver-como-usuario': {
      id: '/admin/_shell/ver-como-usuario'
      path: '/ver-como-usuario'
      fullPath: '/admin/ver-como-usuario'
      preLoaderRoute: typeof AdminShellVerComoUsuarioRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/usuarios': {
      id: '/admin/_shell/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminShellUsuariosRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/templates': {
      id: '/admin/_shell/templates'
      path: '/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminShellTemplatesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/qa-capas': {
      id: '/admin/_shell/qa-capas'
      path: '/qa-capas'
      fullPath: '/admin/qa-capas'
      preLoaderRoute: typeof AdminShellQaCapasRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/planos': {
      id: '/admin/_shell/planos'
      path: '/planos'
      fullPath: '/admin/planos'
      preLoaderRoute: typeof AdminShellPlanosRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/ofertas': {
      id: '/admin/_shell/ofertas'
      path: '/ofertas'
      fullPath: '/admin/ofertas'
      preLoaderRoute: typeof AdminShellOfertasRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/idiomas': {
      id: '/admin/_shell/idiomas'
      path: '/idiomas'
      fullPath: '/admin/idiomas'
      preLoaderRoute: typeof AdminShellIdiomasRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/hospedar-videos': {
      id: '/admin/_shell/hospedar-videos'
      path: '/hospedar-videos'
      fullPath: '/admin/hospedar-videos'
      preLoaderRoute: typeof AdminShellHospedarVideosRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/espionar-ofertas': {
      id: '/admin/_shell/espionar-ofertas'
      path: '/espionar-ofertas'
      fullPath: '/admin/espionar-ofertas'
      preLoaderRoute: typeof AdminShellEspionarOfertasRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/dashboard': {
      id: '/admin/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminShellDashboardRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/criar-quiz': {
      id: '/admin/_shell/criar-quiz'
      path: '/criar-quiz'
      fullPath: '/admin/criar-quiz'
      preLoaderRoute: typeof AdminShellCriarQuizRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/criar-e-clonar-sites': {
      id: '/admin/_shell/criar-e-clonar-sites'
      path: '/criar-e-clonar-sites'
      fullPath: '/admin/criar-e-clonar-sites'
      preLoaderRoute: typeof AdminShellCriarEClonarSitesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/cores': {
      id: '/admin/_shell/cores'
      path: '/cores'
      fullPath: '/admin/cores'
      preLoaderRoute: typeof AdminShellCoresRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/catalogo': {
      id: '/admin/_shell/catalogo'
      path: '/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AdminShellCatalogoRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/cadastrar-produto': {
      id: '/admin/_shell/cadastrar-produto'
      path: '/cadastrar-produto'
      fullPath: '/admin/cadastrar-produto'
      preLoaderRoute: typeof AdminShellCadastrarProdutoRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/cadastrar-perfect-pay': {
      id: '/admin/_shell/cadastrar-perfect-pay'
      path: '/cadastrar-perfect-pay'
      fullPath: '/admin/cadastrar-perfect-pay'
      preLoaderRoute: typeof AdminShellCadastrarPerfectPayRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/branding': {
      id: '/admin/_shell/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AdminShellBrandingRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/areas-membros': {
      id: '/admin/_shell/areas-membros'
      path: '/areas-membros'
      fullPath: '/admin/areas-membros'
      preLoaderRoute: typeof AdminShellAreasMembrosRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/areas': {
      id: '/admin/_shell/areas'
      path: '/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AdminShellAreasRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/api/public/perfectpay/webhook': {
      id: '/api/public/perfectpay/webhook'
      path: '/api/public/perfectpay/webhook'
      fullPath: '/api/public/perfectpay/webhook'
      preLoaderRoute: typeof ApiPublicPerfectpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/usuarios/$userId': {
      id: '/admin/_shell/usuarios/$userId'
      path: '/$userId'
      fullPath: '/admin/usuarios/$userId'
      preLoaderRoute: typeof AdminShellUsuariosUserIdRouteImport
      parentRoute: typeof AdminShellUsuariosRoute
    }
    '/admin/_shell/ferramentas/$slug': {
      id: '/admin/_shell/ferramentas/$slug'
      path: '/ferramentas/$slug'
      fullPath: '/admin/ferramentas/$slug'
      preLoaderRoute: typeof AdminShellFerramentasSlugRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/biblioteca/downloads': {
      id: '/admin/_shell/biblioteca/downloads'
      path: '/biblioteca/downloads'
      fullPath: '/admin/biblioteca/downloads'
      preLoaderRoute: typeof AdminShellBibliotecaDownloadsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/biblioteca/desenhos': {
      id: '/admin/_shell/biblioteca/desenhos'
      path: '/biblioteca/desenhos'
      fullPath: '/admin/biblioteca/desenhos'
      preLoaderRoute: typeof AdminShellBibliotecaDesenhosRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/biblioteca/cursos': {
      id: '/admin/_shell/biblioteca/cursos'
      path: '/biblioteca/cursos'
      fullPath: '/admin/biblioteca/cursos'
      preLoaderRoute: typeof AdminShellBibliotecaCursosRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/areas/$areaId': {
      id: '/admin/_shell/areas/$areaId'
      path: '/$areaId'
      fullPath: '/admin/areas/$areaId'
      preLoaderRoute: typeof AdminShellAreasAreaIdRouteImport
      parentRoute: typeof AdminShellAreasRoute
    }
    '/admin/_shell/produtos/$productId/ebook': {
      id: '/admin/_shell/produtos/$productId/ebook'
      path: '/produtos/$productId/ebook'
      fullPath: '/admin/produtos/$productId/ebook'
      preLoaderRoute: typeof AdminShellProdutosProductIdEbookRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/produtos/$productId/aulas': {
      id: '/admin/_shell/produtos/$productId/aulas'
      path: '/produtos/$productId/aulas'
      fullPath: '/admin/produtos/$productId/aulas'
      preLoaderRoute: typeof AdminShellProdutosProductIdAulasRouteImport
      parentRoute: typeof AdminShellRoute
    }
  }
}

interface PerfilRouteChildren {
  PerfilComprasRoute: typeof PerfilComprasRoute
  PerfilExplorarRoute: typeof PerfilExplorarRoute
  PerfilIndexRoute: typeof PerfilIndexRoute
}

const PerfilRouteChildren: PerfilRouteChildren = {
  PerfilComprasRoute: PerfilComprasRoute,
  PerfilExplorarRoute: PerfilExplorarRoute,
  PerfilIndexRoute: PerfilIndexRoute,
}

const PerfilRouteWithChildren =
  PerfilRoute._addFileChildren(PerfilRouteChildren)

interface AdminShellAreasRouteChildren {
  AdminShellAreasAreaIdRoute: typeof AdminShellAreasAreaIdRoute
}

const AdminShellAreasRouteChildren: AdminShellAreasRouteChildren = {
  AdminShellAreasAreaIdRoute: AdminShellAreasAreaIdRoute,
}

const AdminShellAreasRouteWithChildren = AdminShellAreasRoute._addFileChildren(
  AdminShellAreasRouteChildren,
)

interface AdminShellUsuariosRouteChildren {
  AdminShellUsuariosUserIdRoute: typeof AdminShellUsuariosUserIdRoute
}

const AdminShellUsuariosRouteChildren: AdminShellUsuariosRouteChildren = {
  AdminShellUsuariosUserIdRoute: AdminShellUsuariosUserIdRoute,
}

const AdminShellUsuariosRouteWithChildren =
  AdminShellUsuariosRoute._addFileChildren(AdminShellUsuariosRouteChildren)

interface AdminShellRouteChildren {
  AdminShellAreasRoute: typeof AdminShellAreasRouteWithChildren
  AdminShellAreasMembrosRoute: typeof AdminShellAreasMembrosRoute
  AdminShellBrandingRoute: typeof AdminShellBrandingRoute
  AdminShellCadastrarPerfectPayRoute: typeof AdminShellCadastrarPerfectPayRoute
  AdminShellCadastrarProdutoRoute: typeof AdminShellCadastrarProdutoRoute
  AdminShellCatalogoRoute: typeof AdminShellCatalogoRoute
  AdminShellCoresRoute: typeof AdminShellCoresRoute
  AdminShellCriarEClonarSitesRoute: typeof AdminShellCriarEClonarSitesRoute
  AdminShellCriarQuizRoute: typeof AdminShellCriarQuizRoute
  AdminShellDashboardRoute: typeof AdminShellDashboardRoute
  AdminShellEspionarOfertasRoute: typeof AdminShellEspionarOfertasRoute
  AdminShellHospedarVideosRoute: typeof AdminShellHospedarVideosRoute
  AdminShellIdiomasRoute: typeof AdminShellIdiomasRoute
  AdminShellOfertasRoute: typeof AdminShellOfertasRoute
  AdminShellPlanosRoute: typeof AdminShellPlanosRoute
  AdminShellQaCapasRoute: typeof AdminShellQaCapasRoute
  AdminShellTemplatesRoute: typeof AdminShellTemplatesRoute
  AdminShellUsuariosRoute: typeof AdminShellUsuariosRouteWithChildren
  AdminShellVerComoUsuarioRoute: typeof AdminShellVerComoUsuarioRoute
  AdminShellWebhooksRoute: typeof AdminShellWebhooksRoute
  AdminShellBibliotecaCursosRoute: typeof AdminShellBibliotecaCursosRoute
  AdminShellBibliotecaDesenhosRoute: typeof AdminShellBibliotecaDesenhosRoute
  AdminShellBibliotecaDownloadsRoute: typeof AdminShellBibliotecaDownloadsRoute
  AdminShellFerramentasSlugRoute: typeof AdminShellFerramentasSlugRoute
  AdminShellProdutosProductIdAulasRoute: typeof AdminShellProdutosProductIdAulasRoute
  AdminShellProdutosProductIdEbookRoute: typeof AdminShellProdutosProductIdEbookRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellAreasRoute: AdminShellAreasRouteWithChildren,
  AdminShellAreasMembrosRoute: AdminShellAreasMembrosRoute,
  AdminShellBrandingRoute: AdminShellBrandingRoute,
  AdminShellCadastrarPerfectPayRoute: AdminShellCadastrarPerfectPayRoute,
  AdminShellCadastrarProdutoRoute: AdminShellCadastrarProdutoRoute,
  AdminShellCatalogoRoute: AdminShellCatalogoRoute,
  AdminShellCoresRoute: AdminShellCoresRoute,
  AdminShellCriarEClonarSitesRoute: AdminShellCriarEClonarSitesRoute,
  AdminShellCriarQuizRoute: AdminShellCriarQuizRoute,
  AdminShellDashboardRoute: AdminShellDashboardRoute,
  AdminShellEspionarOfertasRoute: AdminShellEspionarOfertasRoute,
  AdminShellHospedarVideosRoute: AdminShellHospedarVideosRoute,
  AdminShellIdiomasRoute: AdminShellIdiomasRoute,
  AdminShellOfertasRoute: AdminShellOfertasRoute,
  AdminShellPlanosRoute: AdminShellPlanosRoute,
  AdminShellQaCapasRoute: AdminShellQaCapasRoute,
  AdminShellTemplatesRoute: AdminShellTemplatesRoute,
  AdminShellUsuariosRoute: AdminShellUsuariosRouteWithChildren,
  AdminShellVerComoUsuarioRoute: AdminShellVerComoUsuarioRoute,
  AdminShellWebhooksRoute: AdminShellWebhooksRoute,
  AdminShellBibliotecaCursosRoute: AdminShellBibliotecaCursosRoute,
  AdminShellBibliotecaDesenhosRoute: AdminShellBibliotecaDesenhosRoute,
  AdminShellBibliotecaDownloadsRoute: AdminShellBibliotecaDownloadsRoute,
  AdminShellFerramentasSlugRoute: AdminShellFerramentasSlugRoute,
  AdminShellProdutosProductIdAulasRoute: AdminShellProdutosProductIdAulasRoute,
  AdminShellProdutosProductIdEbookRoute: AdminShellProdutosProductIdEbookRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscarRoute: BuscarRoute,
  FavoritosRoute: FavoritosRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRouteWithChildren,
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  PintarSlugPageRoute: PintarSlugPageRoute,
  ApiPublicPerfectpayWebhookRoute: ApiPublicPerfectpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
